# Generated by Django 4.0.4 on 2022-07-11 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('junho', '0002_board_boardcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='dt_modified',
            new_name='modified_date',
        ),
        migrations.RemoveField(
            model_name='board',
            name='dt_created',
        ),
        migrations.AddField(
            model_name='board',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
