# Generated by Django 4.0.4 on 2022-07-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junho', '0003_rename_dt_modified_board_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='board_id',
            field=models.ForeignKey(db_column='board_id', on_delete=django.db.models.deletion.CASCADE, related_name='boardcomment', to='junho.board'),
        ),
    ]
