# Generated by Django 4.0.4 on 2022-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junho', '0004_alter_boardcomment_board_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
