# Generated by Django 4.0.4 on 2022-07-27 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junho', '0005_board_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='junho.boardcomment'),
        ),
    ]
