# Generated by Django 4.0.4 on 2022-07-27 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('junho', '0006_boardcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='board_id',
            field=models.ForeignKey(db_column='board_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boardcomment', to='junho.board'),
        ),
    ]
